/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "https://esm.sh/ethers@6.7.0";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common.ts";

export interface HashtagTradeWithReferralInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchClaimHolderFees"
      | "batchClaimableHolderFees"
      | "buy"
      | "claimHolderFee"
      | "claimableHolderFee"
      | "endMigration"
      | "forceBatchClaimHolderFees"
      | "getBuyPrice"
      | "getBuyPriceAfterFee"
      | "getPrice"
      | "getSellPrice"
      | "getSellPriceAfterFee"
      | "hashtags"
      | "holderFeePercent"
      | "holders"
      | "initialize"
      | "migrate"
      | "migrated"
      | "oracleAddress"
      | "owner"
      | "protocolFeeDestination"
      | "protocolFeePercent"
      | "referralFeePercent"
      | "renounceOwnership"
      | "sell"
      | "setHolderFeePercent"
      | "setOracleAddress"
      | "setProtocolFeeDestination"
      | "setProtocolFeePercent"
      | "setReferralFeePercent"
      | "signingNonce"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ClaimHolderFee"
      | "EndMigration"
      | "Initialized"
      | "MigrateHolder"
      | "OwnershipTransferred"
      | "SetHolderFeePercent"
      | "SetOracleAddress"
      | "SetProtocolFeeDestination"
      | "SetProtocolFeePercent"
      | "SetReferralFeePercent"
      | "Trade"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchClaimHolderFees",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchClaimableHolderFees",
    values: [BytesLike[], AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [BytesLike, BigNumberish, BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimHolderFee",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimableHolderFee",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "endMigration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "forceBatchClaimHolderFees",
    values: [BytesLike[], AddressLike[][]]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyPrice",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyPriceAfterFee",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellPrice",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellPriceAfterFee",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "hashtags", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "holderFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "holders",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "migrate",
    values: [BytesLike[], AddressLike[][], BigNumberish[][]]
  ): string;
  encodeFunctionData(functionFragment: "migrated", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "oracleAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolFeeDestination",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "referralFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sell",
    values: [BytesLike, BigNumberish, BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setHolderFeePercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setOracleAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFeeDestination",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFeePercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setReferralFeePercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "signingNonce",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchClaimHolderFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchClaimableHolderFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimHolderFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableHolderFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "endMigration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceBatchClaimHolderFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyPriceAfterFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSellPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSellPriceAfterFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hashtags", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "holderFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "holders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "migrate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "migrated", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "oracleAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeDestination",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "referralFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setHolderFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOracleAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFeeDestination",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReferralFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signingNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ClaimHolderFeeEvent {
  export type InputTuple = [
    holder: AddressLike,
    hashtag: BytesLike,
    fee: BigNumberish
  ];
  export type OutputTuple = [holder: string, hashtag: string, fee: bigint];
  export interface OutputObject {
    holder: string;
    hashtag: string;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EndMigrationEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MigrateHolderEvent {
  export type InputTuple = [
    hashtag: BytesLike,
    holder: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [hashtag: string, holder: string, amount: bigint];
  export interface OutputObject {
    hashtag: string;
    holder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetHolderFeePercentEvent {
  export type InputTuple = [percent: BigNumberish];
  export type OutputTuple = [percent: bigint];
  export interface OutputObject {
    percent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetOracleAddressEvent {
  export type InputTuple = [oracle: AddressLike];
  export type OutputTuple = [oracle: string];
  export interface OutputObject {
    oracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetProtocolFeeDestinationEvent {
  export type InputTuple = [destination: AddressLike];
  export type OutputTuple = [destination: string];
  export interface OutputObject {
    destination: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetProtocolFeePercentEvent {
  export type InputTuple = [percent: BigNumberish];
  export type OutputTuple = [percent: bigint];
  export interface OutputObject {
    percent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetReferralFeePercentEvent {
  export type InputTuple = [percent: BigNumberish];
  export type OutputTuple = [percent: bigint];
  export interface OutputObject {
    percent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeEvent {
  export type InputTuple = [
    trader: AddressLike,
    hashtag: BytesLike,
    isBuy: boolean,
    amount: BigNumberish,
    price: BigNumberish,
    protocolFee: BigNumberish,
    holderFee: BigNumberish,
    additionalFee: BigNumberish,
    referrer: AddressLike,
    referrerFee: BigNumberish,
    supply: BigNumberish
  ];
  export type OutputTuple = [
    trader: string,
    hashtag: string,
    isBuy: boolean,
    amount: bigint,
    price: bigint,
    protocolFee: bigint,
    holderFee: bigint,
    additionalFee: bigint,
    referrer: string,
    referrerFee: bigint,
    supply: bigint
  ];
  export interface OutputObject {
    trader: string;
    hashtag: string;
    isBuy: boolean;
    amount: bigint;
    price: bigint;
    protocolFee: bigint;
    holderFee: bigint;
    additionalFee: bigint;
    referrer: string;
    referrerFee: bigint;
    supply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HashtagTradeWithReferral extends BaseContract {
  connect(runner?: ContractRunner | null): HashtagTradeWithReferral;
  waitForDeployment(): Promise<this>;

  interface: HashtagTradeWithReferralInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchClaimHolderFees: TypedContractMethod<
    [_hashtags: BytesLike[]],
    [void],
    "nonpayable"
  >;

  batchClaimableHolderFees: TypedContractMethod<
    [_hashtags: BytesLike[], holder: AddressLike],
    [bigint[]],
    "view"
  >;

  buy: TypedContractMethod<
    [
      hashtag: BytesLike,
      amount: BigNumberish,
      additionalFeePercent: BigNumberish,
      referrer: AddressLike,
      oracleSignature: BytesLike
    ],
    [void],
    "payable"
  >;

  claimHolderFee: TypedContractMethod<
    [hashtag: BytesLike],
    [void],
    "nonpayable"
  >;

  claimableHolderFee: TypedContractMethod<
    [hashtag: BytesLike, holder: AddressLike],
    [bigint],
    "view"
  >;

  endMigration: TypedContractMethod<[], [void], "nonpayable">;

  forceBatchClaimHolderFees: TypedContractMethod<
    [_hashtags: BytesLike[], _holders: AddressLike[][]],
    [void],
    "nonpayable"
  >;

  getBuyPrice: TypedContractMethod<
    [hashtag: BytesLike, amount: BigNumberish],
    [bigint],
    "view"
  >;

  getBuyPriceAfterFee: TypedContractMethod<
    [hashtag: BytesLike, amount: BigNumberish],
    [bigint],
    "view"
  >;

  getPrice: TypedContractMethod<
    [supply: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;

  getSellPrice: TypedContractMethod<
    [hashtag: BytesLike, amount: BigNumberish],
    [bigint],
    "view"
  >;

  getSellPriceAfterFee: TypedContractMethod<
    [hashtag: BytesLike, amount: BigNumberish],
    [bigint],
    "view"
  >;

  hashtags: TypedContractMethod<
    [arg0: BytesLike],
    [[bigint, bigint] & { supply: bigint; accFeePerUnit: bigint }],
    "view"
  >;

  holderFeePercent: TypedContractMethod<[], [bigint], "view">;

  holders: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [[bigint, bigint] & { balance: bigint; feeDebt: bigint }],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      _baseDivider: BigNumberish,
      _protocolFeeDestination: AddressLike,
      _protocolFeePercent: BigNumberish,
      _holderFeePercent: BigNumberish,
      _oracleAddress: AddressLike,
      _referralFeePercent: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  migrate: TypedContractMethod<
    [
      _hashtags: BytesLike[],
      allHolders: AddressLike[][],
      allAmounts: BigNumberish[][]
    ],
    [void],
    "nonpayable"
  >;

  migrated: TypedContractMethod<[], [boolean], "view">;

  oracleAddress: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  protocolFeeDestination: TypedContractMethod<[], [string], "view">;

  protocolFeePercent: TypedContractMethod<[], [bigint], "view">;

  referralFeePercent: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sell: TypedContractMethod<
    [
      hashtag: BytesLike,
      amount: BigNumberish,
      additionalFeeRatio: BigNumberish,
      referrer: AddressLike,
      oracleSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setHolderFeePercent: TypedContractMethod<
    [_feePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  setOracleAddress: TypedContractMethod<
    [_oracle: AddressLike],
    [void],
    "nonpayable"
  >;

  setProtocolFeeDestination: TypedContractMethod<
    [_feeDestination: AddressLike],
    [void],
    "nonpayable"
  >;

  setProtocolFeePercent: TypedContractMethod<
    [_feePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  setReferralFeePercent: TypedContractMethod<
    [_feePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  signingNonce: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchClaimHolderFees"
  ): TypedContractMethod<[_hashtags: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "batchClaimableHolderFees"
  ): TypedContractMethod<
    [_hashtags: BytesLike[], holder: AddressLike],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<
    [
      hashtag: BytesLike,
      amount: BigNumberish,
      additionalFeePercent: BigNumberish,
      referrer: AddressLike,
      oracleSignature: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "claimHolderFee"
  ): TypedContractMethod<[hashtag: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimableHolderFee"
  ): TypedContractMethod<
    [hashtag: BytesLike, holder: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "endMigration"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "forceBatchClaimHolderFees"
  ): TypedContractMethod<
    [_hashtags: BytesLike[], _holders: AddressLike[][]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBuyPrice"
  ): TypedContractMethod<
    [hashtag: BytesLike, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBuyPriceAfterFee"
  ): TypedContractMethod<
    [hashtag: BytesLike, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<
    [supply: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSellPrice"
  ): TypedContractMethod<
    [hashtag: BytesLike, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSellPriceAfterFee"
  ): TypedContractMethod<
    [hashtag: BytesLike, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashtags"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [[bigint, bigint] & { supply: bigint; accFeePerUnit: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "holderFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "holders"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [[bigint, bigint] & { balance: bigint; feeDebt: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _baseDivider: BigNumberish,
      _protocolFeeDestination: AddressLike,
      _protocolFeePercent: BigNumberish,
      _holderFeePercent: BigNumberish,
      _oracleAddress: AddressLike,
      _referralFeePercent: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "migrate"
  ): TypedContractMethod<
    [
      _hashtags: BytesLike[],
      allHolders: AddressLike[][],
      allAmounts: BigNumberish[][]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "migrated"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "oracleAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolFeeDestination"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "referralFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sell"
  ): TypedContractMethod<
    [
      hashtag: BytesLike,
      amount: BigNumberish,
      additionalFeeRatio: BigNumberish,
      referrer: AddressLike,
      oracleSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setHolderFeePercent"
  ): TypedContractMethod<[_feePercent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOracleAddress"
  ): TypedContractMethod<[_oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setProtocolFeeDestination"
  ): TypedContractMethod<[_feeDestination: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setProtocolFeePercent"
  ): TypedContractMethod<[_feePercent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setReferralFeePercent"
  ): TypedContractMethod<[_feePercent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "signingNonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ClaimHolderFee"
  ): TypedContractEvent<
    ClaimHolderFeeEvent.InputTuple,
    ClaimHolderFeeEvent.OutputTuple,
    ClaimHolderFeeEvent.OutputObject
  >;
  getEvent(
    key: "EndMigration"
  ): TypedContractEvent<
    EndMigrationEvent.InputTuple,
    EndMigrationEvent.OutputTuple,
    EndMigrationEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MigrateHolder"
  ): TypedContractEvent<
    MigrateHolderEvent.InputTuple,
    MigrateHolderEvent.OutputTuple,
    MigrateHolderEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SetHolderFeePercent"
  ): TypedContractEvent<
    SetHolderFeePercentEvent.InputTuple,
    SetHolderFeePercentEvent.OutputTuple,
    SetHolderFeePercentEvent.OutputObject
  >;
  getEvent(
    key: "SetOracleAddress"
  ): TypedContractEvent<
    SetOracleAddressEvent.InputTuple,
    SetOracleAddressEvent.OutputTuple,
    SetOracleAddressEvent.OutputObject
  >;
  getEvent(
    key: "SetProtocolFeeDestination"
  ): TypedContractEvent<
    SetProtocolFeeDestinationEvent.InputTuple,
    SetProtocolFeeDestinationEvent.OutputTuple,
    SetProtocolFeeDestinationEvent.OutputObject
  >;
  getEvent(
    key: "SetProtocolFeePercent"
  ): TypedContractEvent<
    SetProtocolFeePercentEvent.InputTuple,
    SetProtocolFeePercentEvent.OutputTuple,
    SetProtocolFeePercentEvent.OutputObject
  >;
  getEvent(
    key: "SetReferralFeePercent"
  ): TypedContractEvent<
    SetReferralFeePercentEvent.InputTuple,
    SetReferralFeePercentEvent.OutputTuple,
    SetReferralFeePercentEvent.OutputObject
  >;
  getEvent(
    key: "Trade"
  ): TypedContractEvent<
    TradeEvent.InputTuple,
    TradeEvent.OutputTuple,
    TradeEvent.OutputObject
  >;

  filters: {
    "ClaimHolderFee(address,bytes32,uint256)": TypedContractEvent<
      ClaimHolderFeeEvent.InputTuple,
      ClaimHolderFeeEvent.OutputTuple,
      ClaimHolderFeeEvent.OutputObject
    >;
    ClaimHolderFee: TypedContractEvent<
      ClaimHolderFeeEvent.InputTuple,
      ClaimHolderFeeEvent.OutputTuple,
      ClaimHolderFeeEvent.OutputObject
    >;

    "EndMigration()": TypedContractEvent<
      EndMigrationEvent.InputTuple,
      EndMigrationEvent.OutputTuple,
      EndMigrationEvent.OutputObject
    >;
    EndMigration: TypedContractEvent<
      EndMigrationEvent.InputTuple,
      EndMigrationEvent.OutputTuple,
      EndMigrationEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MigrateHolder(bytes32,address,uint256)": TypedContractEvent<
      MigrateHolderEvent.InputTuple,
      MigrateHolderEvent.OutputTuple,
      MigrateHolderEvent.OutputObject
    >;
    MigrateHolder: TypedContractEvent<
      MigrateHolderEvent.InputTuple,
      MigrateHolderEvent.OutputTuple,
      MigrateHolderEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SetHolderFeePercent(uint256)": TypedContractEvent<
      SetHolderFeePercentEvent.InputTuple,
      SetHolderFeePercentEvent.OutputTuple,
      SetHolderFeePercentEvent.OutputObject
    >;
    SetHolderFeePercent: TypedContractEvent<
      SetHolderFeePercentEvent.InputTuple,
      SetHolderFeePercentEvent.OutputTuple,
      SetHolderFeePercentEvent.OutputObject
    >;

    "SetOracleAddress(address)": TypedContractEvent<
      SetOracleAddressEvent.InputTuple,
      SetOracleAddressEvent.OutputTuple,
      SetOracleAddressEvent.OutputObject
    >;
    SetOracleAddress: TypedContractEvent<
      SetOracleAddressEvent.InputTuple,
      SetOracleAddressEvent.OutputTuple,
      SetOracleAddressEvent.OutputObject
    >;

    "SetProtocolFeeDestination(address)": TypedContractEvent<
      SetProtocolFeeDestinationEvent.InputTuple,
      SetProtocolFeeDestinationEvent.OutputTuple,
      SetProtocolFeeDestinationEvent.OutputObject
    >;
    SetProtocolFeeDestination: TypedContractEvent<
      SetProtocolFeeDestinationEvent.InputTuple,
      SetProtocolFeeDestinationEvent.OutputTuple,
      SetProtocolFeeDestinationEvent.OutputObject
    >;

    "SetProtocolFeePercent(uint256)": TypedContractEvent<
      SetProtocolFeePercentEvent.InputTuple,
      SetProtocolFeePercentEvent.OutputTuple,
      SetProtocolFeePercentEvent.OutputObject
    >;
    SetProtocolFeePercent: TypedContractEvent<
      SetProtocolFeePercentEvent.InputTuple,
      SetProtocolFeePercentEvent.OutputTuple,
      SetProtocolFeePercentEvent.OutputObject
    >;

    "SetReferralFeePercent(uint256)": TypedContractEvent<
      SetReferralFeePercentEvent.InputTuple,
      SetReferralFeePercentEvent.OutputTuple,
      SetReferralFeePercentEvent.OutputObject
    >;
    SetReferralFeePercent: TypedContractEvent<
      SetReferralFeePercentEvent.InputTuple,
      SetReferralFeePercentEvent.OutputTuple,
      SetReferralFeePercentEvent.OutputObject
    >;

    "Trade(address,bytes32,bool,uint256,uint256,uint256,uint256,uint256,address,uint256,uint256)": TypedContractEvent<
      TradeEvent.InputTuple,
      TradeEvent.OutputTuple,
      TradeEvent.OutputObject
    >;
    Trade: TypedContractEvent<
      TradeEvent.InputTuple,
      TradeEvent.OutputTuple,
      TradeEvent.OutputObject
    >;
  };
}
